#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ARTIFACTS_DIR="${ARTIFACTS_DIR:-${SCRIPT_DIR}/artifacts}"
WEB_ARTIFACT_DIR="${ARTIFACTS_DIR}/web"
APK_ARTIFACT_DIR="${ARTIFACTS_DIR}/apk"
ICON_SOURCE_FILE="${SCRIPT_DIR}/public/icon_knob_rounded_square.svg"
RELEASE_VERSION="${RELEASE_VERSION:-$(node -p "require(process.argv[1]).version" "${SCRIPT_DIR}/package.json")}"
RELEASE_VERSION="${RELEASE_VERSION#v}"
export VITE_APP_VERSION="${VITE_APP_VERSION:-${RELEASE_VERSION}}"
ANDROID_BUILD_MODE="debug"
ANDROID_BUILD_ARGS=(--apk --debug --ci)
ANDROID_KEYSTORE_FILE=""
ANDROID_KEYSTORE_PATH_RESOLVED=""
ANDROID_APKSIGNER=""
PACKAGE_JSON_BACKUP=""
TAURI_CONF_BACKUP=""
CARGO_TOML_BACKUP=""

cleanup_android_signing() {
  if [ -n "${ANDROID_KEYSTORE_FILE}" ] && [ -f "${ANDROID_KEYSTORE_FILE}" ]; then
    rm -f "${ANDROID_KEYSTORE_FILE}"
  fi

  if [ -f "${SCRIPT_DIR}/src-tauri/gen/android/keystore.properties" ]; then
    rm -f "${SCRIPT_DIR}/src-tauri/gen/android/keystore.properties"
  fi

  if [ -n "${PACKAGE_JSON_BACKUP}" ] && [ -f "${PACKAGE_JSON_BACKUP}" ]; then
    mv "${PACKAGE_JSON_BACKUP}" "${SCRIPT_DIR}/package.json"
  fi

  if [ -n "${TAURI_CONF_BACKUP}" ] && [ -f "${TAURI_CONF_BACKUP}" ]; then
    mv "${TAURI_CONF_BACKUP}" "${SCRIPT_DIR}/src-tauri/tauri.conf.json"
  fi

  if [ -n "${CARGO_TOML_BACKUP}" ] && [ -f "${CARGO_TOML_BACKUP}" ]; then
    mv "${CARGO_TOML_BACKUP}" "${SCRIPT_DIR}/src-tauri/Cargo.toml"
  fi
}

trap cleanup_android_signing EXIT

sync_release_version_files() {
  PACKAGE_JSON_BACKUP="$(mktemp "${ARTIFACTS_DIR}/package.json.XXXXXX")"
  TAURI_CONF_BACKUP="$(mktemp "${ARTIFACTS_DIR}/tauri.conf.json.XXXXXX")"
  CARGO_TOML_BACKUP="$(mktemp "${ARTIFACTS_DIR}/Cargo.toml.XXXXXX")"

  cp "${SCRIPT_DIR}/package.json" "${PACKAGE_JSON_BACKUP}"
  cp "${SCRIPT_DIR}/src-tauri/tauri.conf.json" "${TAURI_CONF_BACKUP}"
  cp "${SCRIPT_DIR}/src-tauri/Cargo.toml" "${CARGO_TOML_BACKUP}"

  node - "${SCRIPT_DIR}/package.json" "${RELEASE_VERSION}" <<'NODE'
const fs = require("fs");
const [filePath, version] = process.argv.slice(2);
const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
data.version = version;
fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`);
NODE

  node - "${SCRIPT_DIR}/src-tauri/tauri.conf.json" "${RELEASE_VERSION}" <<'NODE'
const fs = require("fs");
const [filePath, version] = process.argv.slice(2);
const data = JSON.parse(fs.readFileSync(filePath, "utf8"));
data.version = version;
fs.writeFileSync(filePath, `${JSON.stringify(data, null, 2)}\n`);
NODE

  perl -0pi -e 's/^version = ".*"$/version = "'"${RELEASE_VERSION}"'"/m' "${SCRIPT_DIR}/src-tauri/Cargo.toml"
}

write_android_version_properties() {
  local version_core prerelease_suffix prerelease_number android_version_code properties_file

  version_core="${RELEASE_VERSION%%-*}"
  if [[ ! "${version_core}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    echo "Error: RELEASE_VERSION must be semantic version-like, got ${RELEASE_VERSION}"
    exit 1
  fi

  local major="${BASH_REMATCH[1]}"
  local minor="${BASH_REMATCH[2]}"
  local patch="${BASH_REMATCH[3]}"

  prerelease_suffix=""
  prerelease_number=99
  if [[ "${RELEASE_VERSION}" == *-* ]]; then
    prerelease_suffix="${RELEASE_VERSION#*-}"
    prerelease_number=0
    if [[ "${prerelease_suffix}" =~ \.([0-9]+)$ ]]; then
      prerelease_number="${BASH_REMATCH[1]}"
    fi
  fi

  android_version_code=$((major * 1000000 + minor * 10000 + patch * 100 + prerelease_number))
  properties_file="${SCRIPT_DIR}/src-tauri/gen/android/app/tauri.properties"

  cat > "${properties_file}" <<EOF
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=${RELEASE_VERSION}
tauri.android.versionCode=${android_version_code}
EOF
}

resolve_apksigner() {
  if [ -n "${ANDROID_APKSIGNER}" ]; then
    return
  fi

  if command -v apksigner >/dev/null 2>&1; then
    ANDROID_APKSIGNER="$(command -v apksigner)"
    return
  fi

  local sdk_root="${ANDROID_HOME:-${ANDROID_SDK_ROOT:-$HOME/Library/Android/sdk}}"
  ANDROID_APKSIGNER="$(find "${sdk_root}/build-tools" -type f -name apksigner 2>/dev/null | sort -Vr | head -n 1)"
  if [ -z "${ANDROID_APKSIGNER}" ]; then
    echo "Error: apksigner was not found."
    exit 1
  fi
}

configure_android_signing() {
  if [ -n "${ANDROID_KEY_ALIAS:-}" ] && [ -n "${ANDROID_KEY_PASSWORD:-}" ] && [ -n "${ANDROID_KEY_BASE64:-}" ]; then
    ANDROID_BUILD_MODE="release"
    ANDROID_BUILD_ARGS=(--apk --ci)
    ANDROID_KEYSTORE_FILE="$(mktemp "${ARTIFACTS_DIR}/android-keystore.XXXXXX.jks")"
    printf '%s' "${ANDROID_KEY_BASE64}" | base64 --decode > "${ANDROID_KEYSTORE_FILE}"
    ANDROID_KEYSTORE_PATH_RESOLVED="${ANDROID_KEYSTORE_FILE}"
    cat > "${SCRIPT_DIR}/src-tauri/gen/android/keystore.properties" <<EOF
keyAlias=${ANDROID_KEY_ALIAS}
password=${ANDROID_KEY_PASSWORD}
storeFile=${ANDROID_KEYSTORE_PATH_RESOLVED}
EOF
    echo "Android signing configured for release APKs."
  elif [ -n "${ANDROID_KEY_ALIAS:-}" ] && [ -n "${ANDROID_KEY_PASSWORD:-}" ] && [ -n "${ANDROID_KEYSTORE_PATH:-}" ]; then
    if [ ! -f "${ANDROID_KEYSTORE_PATH}" ]; then
      echo "Error: ANDROID_KEYSTORE_PATH does not exist: ${ANDROID_KEYSTORE_PATH}"
      exit 1
    fi
    ANDROID_BUILD_MODE="release"
    ANDROID_BUILD_ARGS=(--apk --ci)
    ANDROID_KEYSTORE_PATH_RESOLVED="${ANDROID_KEYSTORE_PATH}"
    cat > "${SCRIPT_DIR}/src-tauri/gen/android/keystore.properties" <<EOF
keyAlias=${ANDROID_KEY_ALIAS}
password=${ANDROID_KEY_PASSWORD}
storeFile=${ANDROID_KEYSTORE_PATH_RESOLVED}
EOF
    echo "Android signing configured for release APKs from local keystore."
  else
    echo "Android signing secrets not set. Building installable debug APK."
  fi
}

enforce_android_landscape() {
  local manifest_file="${SCRIPT_DIR}/src-tauri/gen/android/app/src/main/AndroidManifest.xml"

  if [ ! -f "${manifest_file}" ]; then
    echo "Error: Android manifest not found at ${manifest_file}"
    exit 1
  fi

  if grep -q 'android:screenOrientation=' "${manifest_file}"; then
    perl -0pi -e 's/android:screenOrientation="[^"]*"/android:screenOrientation="sensorLandscape"/g' "${manifest_file}"
    return
  fi

  perl -0pi -e 's/(android:name="\.MainActivity"\n)/$1            android:screenOrientation="sensorLandscape"\n/' "${manifest_file}"
}

if [ -z "${VITE_GOOGLE_CLIENT_ID:-}" ]; then
  echo "Error: VITE_GOOGLE_CLIENT_ID is required."
  exit 1
fi

if [ -z "${VITE_GOOGLE_DESKTOP_CLIENT_ID:-}" ]; then
  echo "Error: VITE_GOOGLE_DESKTOP_CLIENT_ID is required."
  exit 1
fi

mkdir -p "${ARTIFACTS_DIR}"
rm -rf "${WEB_ARTIFACT_DIR}" "${APK_ARTIFACT_DIR}"
mkdir -p "${WEB_ARTIFACT_DIR}" "${APK_ARTIFACT_DIR}"
sync_release_version_files

echo "Building GitHub Pages bundle..."
bash "${SCRIPT_DIR}/prepare-dev-index.sh"
GH_PAGES=true npm run build
cp -R "${SCRIPT_DIR}/dist/." "${WEB_ARTIFACT_DIR}/"
(
  cd "${ARTIFACTS_DIR}"
  rm -f web-bundle.zip
  zip -qry web-bundle.zip web
)

echo "Building Android APK..."
if [ ! -f "${ICON_SOURCE_FILE}" ]; then
  echo "Error: Android icon source not found at ${ICON_SOURCE_FILE}"
  exit 1
fi

echo "Regenerating native app icons from ${ICON_SOURCE_FILE}..."
npx tauri icon "${ICON_SOURCE_FILE}" -o "${SCRIPT_DIR}/src-tauri/icons"

echo "Reinitializing Android project to refresh generated launcher icons..."
rm -rf "${SCRIPT_DIR}/src-tauri/gen/android"
npx tauri android init --ci --skip-targets-install
if [ -d "${SCRIPT_DIR}/src-tauri/icons/android" ]; then
  echo "Syncing Android launcher resources into generated project..."
  cp -R "${SCRIPT_DIR}/src-tauri/icons/android/." "${SCRIPT_DIR}/src-tauri/gen/android/app/src/main/res/"
fi

enforce_android_landscape
write_android_version_properties
configure_android_signing
npx tauri android build "${ANDROID_BUILD_ARGS[@]}"

apk_files=()
while IFS= read -r apk_file; do
  apk_files+=("${apk_file}")
done < <(find "${SCRIPT_DIR}/src-tauri/gen/android/app/build/outputs/apk" -type f -name "*.apk" | sort)

if [ "${#apk_files[@]}" -eq 0 ]; then
  echo "Error: No APK files were generated."
  exit 1
fi

copied_apk_count=0
for apk_file in "${apk_files[@]}"; do
  apk_name="$(basename "${apk_file}")"
  apk_name="${apk_name#app-}"
  if [[ "${apk_file}" == *-unsigned.apk ]]; then
    if [ "${ANDROID_BUILD_MODE}" != "release" ]; then
      continue
    fi
    resolve_apksigner
    apk_name="${apk_name/-unsigned/}"
    if [[ "${apk_name}" != 303util* ]]; then
      apk_name="303util-${RELEASE_VERSION}-${apk_name}"
    fi
    "${ANDROID_APKSIGNER}" sign \
      --ks "${ANDROID_KEYSTORE_PATH_RESOLVED}" \
      --ks-key-alias "${ANDROID_KEY_ALIAS}" \
      --ks-pass "pass:${ANDROID_KEY_PASSWORD}" \
      --key-pass "pass:${ANDROID_KEY_PASSWORD}" \
      --out "${APK_ARTIFACT_DIR}/${apk_name}" \
      "${apk_file}"
    copied_apk_count=$((copied_apk_count + 1))
    continue
  fi
  if [[ "${apk_name}" != 303util* ]]; then
    apk_name="303util-${RELEASE_VERSION}-${apk_name}"
  fi
  cp "${apk_file}" "${APK_ARTIFACT_DIR}/${apk_name}"
  copied_apk_count=$((copied_apk_count + 1))
done

if [ "${copied_apk_count}" -eq 0 ]; then
  echo "Error: No installable APK files were found after the ${ANDROID_BUILD_MODE} build."
  exit 1
fi

echo "Artifacts ready in ${ARTIFACTS_DIR}"
